---
- hosts: localhost
  connection: local
  gather_facts: True
  tasks:
    - name: Build Playframework Dist package
      command: chdir=../ sbt "project likeML" dist

- hosts: [like_ml_job]
  sudo: True
  serial: 1
  vars:
    app_name: 'like-ml'
    app_version: '1.0.0'
  tasks:
    - debug: msg="location={{ inventory_hostname }}"
  roles:
    - { role: 'ansible-sbt-java-app' }


