---
kafka_conf_dir: /etc/kafka
kafka_data_dir: /var/kafka
kafka_group: kafka
kafka_user: kafka
kafka_log_dir: /var/log/kafka
kafka_upstart_conf: /etc/init/kafka.conf
kafka_systemd_service: /etc/systemd/system/kafka.service
kafka_port: 9092
kafka_hostname: "{{ansible_hostname}}"

zookeeper_client_port: "2181"
zookeeper_hostnames: "{{ inventory_hostname }}:{{ zookeeper_client_port }}"