---
galaxy_info:
  author: Vlad Dem
  description: Install InfluxDB 0.9
  license: MIT
  min_ansible_version: 1.8
  platforms:
  - name: EL
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  categories:
  - database
  - database:nosql
